config/routes.rb
FeedbackMvp::Application.routes.draw do

  root :to => 'feedbacks#index'

  resources :feedbacks

  get '/presentation' => 'presentations#index', as: 'presentation'
  get '/feedbacks/:id/delete' => 'feedbacks#destroy', as: 'destroy'
end


# Rake routes
#          root        /                               feedbacks#index
#     feedbacks GET    /feedbacks(.:format)            feedbacks#index
#               POST   /feedbacks(.:format)            feedbacks#create
#  new_feedback GET    /feedbacks/new(.:format)        feedbacks#new
# edit_feedback GET    /feedbacks/:id/edit(.:format)   feedbacks#edit
#      feedback GET    /feedbacks/:id(.:format)        feedbacks#show
#               PUT    /feedbacks/:id(.:format)        feedbacks#update
#               DELETE /feedbacks/:id(.:format)        feedbacks#destroy
#  presentation GET    /presentation(.:format)         presentation#index
#       destroy GET    /feedbacks/:id/delete(.:format) feedbacks#destroy

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :name, :description, :weight, :date, :image_url, :media_link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	# Display all feedbacks
	def index
		@all_feedbacks = Feedback.all
	end

	def new
		@feedback = Feedback.new(date: Time.now.strftime("%d/%m/%Y"))
	end

	def create
		feedback = Feedback.create(params[:feedback])

		redirect_to feedbacks_path
	end

	def edit
		@feedback = Feedback.find(params[:id])
	end

	def update
		feedback = Feedback.find(params[:id])
		feedback.update_attributes(params[:feedback])

		redirect_to feedbacks_path
	end

	def destroy
		@feedback = Feedback.find(params[:id])
		@feedback.delete

		redirect_to feedbacks_path
	end

end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
	# Display only top 5 feedbacks
	def index
		@all_feedbacks = Feedback.order("weight DESC").limit(5)


		# With a little more time I would build out a json request and package the @all_feedbacks
		# into a hash and have all the info loaded onto the front end
		# from there I'd add buttons for each 5 feedbacks and use jQuery to have them animate onto the screen

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feedbacks/_form.html.erb
<h1>Add Feedback</h1>

<%= form_for feedback do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br />
	<%= f.label :description %>
	<%= f.text_area :description %>
	<br />
	<%= f.label :weight %>
	<%= f.select :weight, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]] %>
	<br />
	<%= f.label :date %>
	<%= f.date_select :date %>
	<br />
	<%= f.label :image_url %>
	<%= f.text_field :image_url %>
	<br />
	<%= f.label :media_link %>
	<%= f.text_field :media_link %>
	<br />
	<%= f.submit %>
<% end %>

app/views/feedbacks/edit.html.erb
<%= render partial: 'form', locals: {feedback: @feedback} %>

<%= link_to :back %>

app/views/feedbacks/index.html.erb
<h1>Feedbacks Index Page</h1>

<%= link_to 'Add Feedback', new_feedback_path %>
<hr>

<% @all_feedbacks.each do |feedback| %>
<ul>
	<li>Name: <%= feedback.name %> <br />
		Description: <p><%= feedback.description%></p>
		Priority / Weight: <%= feedback.weight %><br />
		Date: <%= feedback.date.strftime("%m/%d/%Y") %></br />
		Image: <img src="<%= feedback.image_url %>"/><br />
		Media: <a href="<%= feedback.media_link %>"><%= feedback.media_link %></a><br />

		<%= link_to 'edit feedback', edit_feedback_path(feedback) %><br />
		<%= link_to 'delete feedback', destroy_path(feedback) %><br />
		<hr>
	</li>
</ul>
<% end %>

<%= link_to 'Client Presentation Link', presentation_path %>

app/views/feedbacks/new.html.erb
<%= render partial: 'form', locals: {feedback: @feedback} %>

<%= link_to :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedbackMvp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/presentations/index.html.erb
<div id='header'>
	<h1>Top 5 Feedback Responses</h1>
</div>

<div id="container">
	<% @all_feedbacks.each do |feedback| %>
	<h3><%= feedback.name %></h3><br />
	Description: <%= feedback.description %><br />
	<br />
	<img src="<%= feedback.image_url %>"/><br />
	<br />
	Video Demo: <a href="<%= feedback.media_link %>"><%= feedback.media_link %></a><br />
	<hr>
	<% end %>
</div>